command_timeout = 1000
scan_timeout = 100

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[kubernetes]
disabled = false
style= "cyan bold"
format = 'on [⛵ $context \($namespace\)](blue) '

[terraform]
format = 'via [$version]($style) '

[container]
format = '[$symbol \[$name\]]($style) '

[line_break]
disabled = true
